lock dependencies (dragoon/komodo!222)
## the issue
in both the base repo and the mirror, for all branches:
```
 error: rustc 1.78.0 is not supported by the following packages:
  rayon@1.11.0 requires rustc 1.80
  rayon-core@1.13.0 requires rustc 1.80
  rayon-core@1.13.0 requires rustc 1.80
  rayon-core@1.13.0 requires rustc 1.80
Either upgrade rustc or select compatible dependency versions with
`cargo update <name>@<current-ver> --precise <compatible-ver>`
where `<compatible-ver>` is the latest version supporting rustc 1.78.0
```

## the fix
as pinning `rayon@1.10.0` (the version in my local `Cargo.lock`) in `Cargo.toml` does not work, i had to start tracking `Cargo.lock`.

this adds a script to check that the lock file has not been modified after running the full CI suite.